package pietanze;

public enum EnumIngredienti {
    STRAWBERRIES, CHOCALATE, COCOA, COFFEE, BUTTER, MILK, EGGS, SUGAR, YEAST, MILK_CREAM, CREAM_CHEESE, MASCARPONE_CHEESE,
    FLOUR, APPLES, DRY_BISCUITS, SAVOIARDI_BISCUITS, HAZELNUTS, SALT, FOOD_COLORING, VANILLA;
}


