qui mettiamo tutti gli script di creazione modifica

Stefano 11/05
----------------------------------------------------------------
/*da controllare tutto, soprattutto le relazioni tra le tabelle (foreign keys)*/

CREATE TABLE RISTORANTE IF NOT EXISTS{
ID_RISTORANTE INT PRIMARY KEY AUTOINCREMENT,
NOME VARCHAR(255) NOT NULL,
INDIRIZZO VARCHAR(255) NOT NULL,
TIPO ENUM() NOT NULL,
FOREIGN KEY (ID_RISTORANTE) REFERENCES RISTORANTE(ID_RISTORANTE);
}

CREATE TABLE MENU IF NOT EXISTS{
ID_MENU INT PRIMARY KEY AUTOINCREMENT,
NOME VARCHAR(255) NOT NULL,
TIPO ENUM() NOT NULL,
FOREIGN KEY (ID_MENU) REFERENCES PORTATA(ID_MENU);
}

CREATE TABLE ORDINE IF NOT EXISTS{
ID_ORDINE INT PRIMARY KEY AUTOINCREMENT,
ID_PORTATA INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_TAVOLO INT NOT NULL,
MANCIA INT NOT NULL,
FOREIGN KEY (ID_ORDINE) REFERENCES PORTATA(ID_ORDINE);
}

CREATE TABLE PORTATA IF NOT EXISTS{
ID_PORTATA INT PRIMARY KEY AUTOINCREMENT,
ID_MENU INT NOT NULL,
ID_ORDINE INT NOT NULL,
NOME VARCHAR(255) NOT NULL,
PREZZO INT NOT NULL,
DESCRIZIONE VARCHAR(255) NOT NULL,
TIPO ENUM() NOT NULL
FOREIGN KEY (ID_PORTATA) REFERENCES ORDINE(ID_PORTATA);
}

CREATE TABLE TAVOLO IF NOT EXISTS{
ID_TAVOLO INT PRIMARY KEY AUTOINCREMENT,
ID_RISTORANTE INT NOT NULL,
DISPONIBILITA INT NOT NULL,
CAPIENZA INT NOT NULL,
DESCRIZIONE VARCHAR(255) NOT NULL,
FOREIGN KEY (ID_TAVOLO) REFERENCES ORDINE(ID_ORDINE);
}

CREATE TABLE CLIENTE IF NOT EXISTS{
ID_CLIENTE INT PRIMARY KEY AUTOINCREMENT,
ETA INT NOT NULL,
NOME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
INDIRIZZO VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
NUMERO_TELEFONO VARCHAR(255) NOT NULL,
NUMERO_CARTA VARCHAR(255) NOT NULL,
DIETA VARCHAR(255) NOT NULL;
FOREIGN KEY (ID_CLIENTE) REFERENCES ORDINE(ID_ORDINE);

----------------------------------------------------------------